### ISSUE TITLE
schematic review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Banker#1]
I did initial [schematics](https://github.com/sinara-hw/Banker/releases/tag/v1.0rc) and component placement.
@jordens @hartytp @dtcallcock @sbourdeauducq please have a look at it.

**Comment by gkasprow** [comment]
I did power supply in such way on purpose. When sb plugs it to LVDS port, 5V would be shorted to GND and PTC fuse will get activated. So nothing would be damaged
I used Molex connector (ATX type) on the PCB rear side. I think in next revision of VHDCI carrier and Kasli we should also use them.  It is much more reliable than DC jacks. In case of DC jacks its possible to not lock it. With Molex one it is really hard.
FPGA FLASH can programmed with 10$ programmer, via I2C or via FPGA itself. I added a circuit that allows FPGA to reboot itself.
Additional circuit makes sure that level translators / buffers get activated some time after FPGA configures and reset pulse is released. All IOs have 10k pulldowns.
I2C is protected with TVS
DIP switch is connected to CSBSEL lines that let us choose which binary to boot or can be used as general purpose config input. It is also connected via 10k to FLASH lines that after configuration can be used as GPIO
Front panel LEDs indicate power, Config DONE, I2C FLASH update mode and user defined signal
I2C switch has its own reset circuit
Translators have 22R resistors towards FPGA. It is to limit the current in case of logic level contention. 
Downstream ports have 300mA PTCs.
I used 6A 5V DC/DC because it is low cost. And when sb drives 128 channels with 25mA it gives already 3.2A

Shall I add 50Ohm resistors at the drivers output? They take some place and I'm not sure if we need impedance matching.

**Comment by jordens** [comment]
Nice!

* Make sure the right pins end up on the GBINs. I'd go for VHDCI0_0, VHDCI1_0, IDC0_0_0, IDC1_0_0, IDC2_0_0, and the 25 MHz clock. On the LVDS bank it's ok.
* I think all the LVDS lines on the three EEM need external termination. Both parallel for input and series for output. Maybe just scrap one downstream EEM if it gets too much.
* The I2C switch reset should be controllable by the FPGA. I see no other way to get out of a hung bus.
* I2C addresses look ok.
* Could we have an easy option to make the TTL level 3.3V (instead of 5V)? Just a couple more resistors/bridges around R367/R368 so that a solder blob will make it 3.3V.
* The drivers have about 10 Ohm output impedance. I'd keep the 30-40 in series. But I see no real need for input parallel termination.
* I don't think the path after IC3 to RSTn to the FPGA is necessary. An internal counter-based delay after configuration should be sufficient. Instead I would drive DRV_OENn from the FPGA (IOL_9B)
* The CFG_RELOAD from the FPGA to CRESET is probably not necessary. There is the SB_WARMBOOT primitive that seems to be able to do that internally. I'd check it though.

* I would put the EEM connectors on the bottom (like Kasli and the others)
* Put the upstream EEM to the right and the downstream ones to the left: "down0, down1, up" from left to right.
* Make sure the bottom (left) VHDCI is VHDCI0 and the top/right VHDCI1.
* Spread out the power and the VHDCI connector as much ass possible on the panel. Without colliding with the handle.
* I'd put the JTAG headers closer to the FPGA.

**Comment by gkasprow** [comment]
@jordens ACK All
To simplify routing of power plane I will use 2.5V for all logics. 
And will get rid of one downlink EEM. Otherwise I would have to use 6 layers for BGA fanout. I'm not sure if it is worth. It would increase the PCB cost by 30%.
Variable supply for TTL would be generated at the main buck converter, so all IOs would be affected. Is that OK?

**Comment by jordens** [comment]
Yes. That's all fine. The alternative would be to have two (3.3/5) domains and split the 128 channels into two power groups. But I don't think that's worth it. People can just get another Banker.

**Comment by gkasprow** [comment]
We can indicate 3.3 / 5V operation with front panel LED.

**Comment by gkasprow** [comment]
I plan to add  series 33R on each DIO + 50Ohm at the other side of the cable.
In this way when driven from very low impedance, the transmission line would be still source-terminated.
When shorted, the driver will dissipate 5V^2/100R, so two 0.125W resistors would be sufficient.

**Comment by jordens** [comment]
Or even 39R.

**Comment by gkasprow** [comment]
Yes, I placed 39 Ohms.

**Comment by gkasprow** [comment]
@jordens to my surprise, I managed to fanout all signals using mainly2 layers. Just a few signals were routed on third layer reserved for power distribution. 
![obraz](https://user-images.githubusercontent.com/4325054/45755173-00026d80-bc1e-11e8-96e7-2159a2374bfa.png)
Altium pin swapping feature was great help here. Please have a look:
[Banker.PDF](https://github.com/sinara-hw/Banker/files/2397721/Banker.PDF)

**Comment by dhslichter** [comment]
How much power dissipation are you going to get if you have 96 channels and each one is driving a 50-ohm terminated load?  The drivers on the schematic will source or sink 32 mA with 5V supply, which means that the logic high will only be 1.6 V across a 50 ohm termination (itself a potential problem).  The dissipation on the board would then be ~100 mW per terminated channel for a logic high, or worst case ~ 10 W.  I think you can't really run a 50 ohm termination at the far end with these lines, would be my point...might have to just plan on the series termination being enough.  You might place a high-current driver on the breakout if you want, for certain channels?

Also, EMI/crosstalk is going to be not great with long cables, and larger currents will make inductive coupling worse....

**Comment by jordens** [comment]
I don't think delivering power into 50 ohms on 128 or even only 32 channels is a design goal. I'd just make sure that the power supply trips in a well defined way before anything blows up.

**Comment by gkasprow** [comment]
I will add LM75 that will shut down the PSU after exceeding 80 degrees...

**Comment by dhslichter** [comment]
All fine.  I just saw comments above talking about terminating loads with 50 ohms at the far end, and I wanted to point out that this is probably not going to work here.  The whole purpose of Banker is to be somewhat time-insensitive digital I/O, though, so I would imagine that they can be made high-impedance inputs.  Series termination at the source will be sufficient for most applications anyway.

**Comment by jordens** [comment]
@gkasprow A couple more things after looking again at the [Lattice LVDS AN](https://www.latticesemi.com/-/media/LatticeSemi/Documents/ApplicationNotes/UZ/UsingDifferentialIOLVDSSubLVDSiniCE40Devices.ashx?document_id=47960):

* The positive LVDS (EEMx_y_P) is generally the B pin (IOL_zB), not the A.
* DBIN7 is special and should be EEM0_0_PN as currently but with polarity swapped.
* I would put EEM0_4_P/N on GBIN6 for another SPI bus on EEM0_4-7.
* LVDS outputs need series resistors (mentioned above) as well. We want some outputs. I'd go for EEM0_{2,6}, EEM1_{0,1,3,4,5,7}, EEM2_{0,1,3,4,5,7}. But if there is space, I'd put those series resistor everywhere.

**Comment by gkasprow** [comment]
It looks like ICE 40 does not implement LVDS transmitters at all. Only receivers.
I though that these resistive networks are needed for sub-LVDS outputs only.
The image:
![obraz](https://user-images.githubusercontent.com/4325054/45814626-79f62d80-bcd6-11e8-848b-346204a1714c.png)
 states that IOL_1A is positive and IOL_1B is negative

they also say:

 _Connect the positive or true polarity side of the differential pair to the DPxxA input and the negative or complementary side of the pair to the DPxxB input._

**Comment by jordens** [comment]
It's just emulated LVDS outputs and differential receivers.
Yeah. Polarity is a bit unclear. But we can invert (data and clock) in gateware.
![image](https://user-images.githubusercontent.com/1338946/45814788-fbe65680-bcd6-11e8-9de4-d2a6b57194f0.png)
![image](https://user-images.githubusercontent.com/1338946/45814800-0b659f80-bcd7-11e8-873b-4e1c4f8b9044.png)

**Comment by gkasprow** [comment]
@jordens we don't care about series resistors in input mode. The inputs are HiZ. So you don't have to change them to 0R.
I used 150R as series resistors + 100R in parallel. In this way we still maintain 100R in input mode and right voltage level in output mode. LVDS is by default not matched on Tx side anyway.

**Comment by gkasprow** [comment]
I didn't swap the diff pairs. It's plenty of work and documentation is not clear. This can be changed in firmware easily. I also added two LM75 thermometers that will shut-down the PSU when board achieves 75 degrees. I will leave the design for a while. Maybe someone will find some other bugs. In the meantime I will design the Humpback and produce them together to make saving on documentation and tooling.

**Comment by jordens** [comment]
Ack. Could you post another rc?

**Comment by gkasprow** [comment]
[done ](https://github.com/sinara-hw/Banker/releases/tag/v1.0rc2)

**Comment by jordens** [comment]
* since the eeprom is behind the switch, identifying banker is now completely different from identifying any other eem. If we risk putting the eeprom on the upstream eem i2c master bus that precludes downstream eeprom at the same address. let's leave it like this.
* The upstream eem should really be the rightmost. Otherwise cabling is extremely annoying. I'd just change the 12v power wire and i2c and declare eem2 (the right most) the upstream one.
* Labels! All connectors (eem, idc26, power, flash config) all test points, all LEDs, the 3.3/5v switch with meaning, and the refdes of the dip switch.

**Comment by jordens** [comment]
* [Banker EDGE2DSUB](https://github.com/sinara-hw/Banker_EDGE_2_DSUB/releases/download/v1.0rc1/Banker_EDGE_2_DSUB.PDF)
* [Banker EDGE2BNC](https://github.com/sinara-hw/Banker_EDGE_2_BNC/releases/download/v1.0rc1/Banker_EDGE_2_BNC.PDF)
* [Banker EDGE2SMA](https://github.com/sinara-hw/Banker_EDGE_2_SMA/releases/download/v1.0rc1/Banker_EDGE_2_SMA.PDF)
* [Banker EDGE2VHDCI](https://github.com/sinara-hw/Banker_VHDCI_2_EDGE/releases/download/v1.0rc1/Banker_VHDCI_2_EDGE.PDF)
* [Banker EDGE2VHDCI Buffered](https://github.com/sinara-hw/Banker_VHDCI_2_EDGE_Buffered/releases/download/v1.0rc1/Banker_VHDCI_2_EDGE_Buffered.PDF)

**Comment by jordens** [comment]
@gkasprow I went through the changes in v1.0rc3. Looks all good. Is the N14/TRST_B change without pulldown because there is no space for routing?

**Comment by gkasprow** [comment]
hm, I connected N14 to GND.

**Comment by jordens** [comment]
Yes. The devboard has a 10k. But gnd is fine afaict.

**Comment by gkasprow** [comment]
@jordens the Banker and other CPCIS EEMs will have large cutout to enable passing EEM cables to neighbouring modules.
![obraz](https://user-images.githubusercontent.com/4325054/50715157-30123700-107c-11e9-9379-7bb464e7cf63.png)

**Comment by jordens** [comment]
Argh. I thought we would make them 160 mm. The cutout is a problem as it prevents one board being pulled unless all cables to the right have been removed.

**Comment by gkasprow** [comment]
It's hard to fit such big connector and other EEM connectors. On Banker it's doaboe but on Urukul would be extremely hard. The idea with 220mm boards was to make it compatible with existing 160mm EEMs by adding adapter board.
CERN also wants to use 220mm boards.
We can make another thing - leave only tab/tabs with CPCIS connectors. Such tab could be cut when not needed and when somebody wants to fit it in 160mm crate
![obraz](https://user-images.githubusercontent.com/4325054/50742725-5caa8800-120f-11e9-914a-1c123e73650b.png)

**Comment by jordens** [comment]
The connector isn't big. It takes only about a third of the board space of the two EEM IDC connectors.
And with that layout it's still hard to fold the ribbon cables up and over the CPCI PCB nose.
Is the tab approach really better than the adapter board approach? If not then I'd just scrap it and simplify the plan by cutting some options. The slew of options and corner cases currently doesn't convince me. Let's stick with 160mm IDC and 220mm CPCI S.0 with adapter boards for now. Once we have enough momentum, we should then switch the entire collection to CPCI S.0 in one clean cut that also gets rid of the IDC cables. Whether that will be CPCI S.0 160 mm or 220 mm is another question.

**Comment by gkasprow** [comment]
Banker involves daisy chain approach that does not comply with backplane anyway. Let's use the adapter idea with following remarks:
- add 2 mouting holes in the corners that will be used to attach such adapter board.
- make sure that position of EEM connectors is same in all EEM boards. In this way in the future we will be able to add rigid version of CPCIS adapter.

We can also move slightly connectors EEM and integrate CPCIs connector with 160mm module, but with such approach we won't have space for IDC cables running to neighbouring Banker boards.
![obraz](https://user-images.githubusercontent.com/4325054/50786411-ca0ff480-12b3-11e9-87f7-92f07f3ebd46.png)

**Comment by gkasprow** [comment]
the CPCIS adapter board can be implemented as directly plugged mezzanine.
CPCIS specification defines "3.6 Mezzanine Concept"
![obraz](https://user-images.githubusercontent.com/4325054/50787260-3be93d80-12b6-11e9-8089-bafce589886f.png)
![obraz](https://user-images.githubusercontent.com/4325054/50787278-460b3c00-12b6-11e9-9e30-0b271384a28b.png)
we can do it not only for P6 buf for P1 as well.
With such approach we could get rid of IDC jumpers. The only requirement is same position of EEM connectors on all EEM modules. Since the newest  release we have for Urukul, we can treat it as the reference for other modules.

**Comment by jordens** [comment]
* Yes! I am all for fixing the EEM IDC positions on all modules and adding the two mounting holes. That adapter board can be pretty small.
* The daisy-chain approach in Banker will work just fine in two cases: (a) for the short modules (DIO*). Maybe this is a good reason to keep them short. and (b) if Banker is the rightmost on the backplane, then there is plenty of space right of it.
* Making the short modules (DIO*, Grabber, Clocker) CPCI S.0-compatible would mean either using Banker (could be a really good idea) or having a longer adapter.
* For that adapter idea, we need a different, mirrored connector style, right?

**Comment by gkasprow** [comment]
It looks like the connectors are symmetrical from mechanical point of view. One need only to make sure the stacking height is 10.8mm.
I plan to order one Schroff chassis, produce adapter board for Banker/Urukul and verify if all fits.

**Comment by gkasprow** [comment]
with such placement we are able to use same adapter for Urukul and Banker. In next Urukul revision we will add only mounting holes.
![obraz](https://user-images.githubusercontent.com/4325054/50795574-fb49ee00-12ce-11e9-9bfc-ff0a3043e403.png)
