### ISSUE TITLE
VHDCI Breakout

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Banker#2]
Greg proposed in [the original Banker RFC](https://github.com/sinara-hw/meta/issues/18#issuecomment-421597904):

**2x 32 channels via VHDCI that can be break-out to 8x D-sub 9 remotely ( on the optical table)**

**If there is interest in other break-out, I can design one.**

And in response to his comments:

> since the VHDCI cable can be already 10m long, does it make sense to make such fanout as 19" form factor? maybe sth smaller that one can put on optical table?

19" is perhaps a bit big for Dsub. However 'on optical table' often means in practice 'in a rack just under/below/beside the optical table'.  Therefore some way of easily adapting the box to rack format is always appreciated, even if it's just a simple bracket like this:

<img width="166" alt="image" src="https://user-images.githubusercontent.com/20587606/45600878-5a52c280-b9c1-11e8-917b-66fc731a9f07.png">

For BNC, wont you end up with something about that size anyway as 24 BNCs is already a whole 1U panel (put the other 8 BNCs and the VHCI on the back)?

> How fast are these pulses? is there any standard pinout for Dsub 9 ?

I don't have a specific use case in mind.  I'm just saying that from experience if I build a simple piece of lab electronics that needs 1 or 2 digital connections I will probably use BNCs.  If it needs 3+ I will probably use a D-sub.  I have pretty much every size, gender and mounting configuration, and a bunch of pre-made cables lying around the lab.  They are of large enough pitch I can easily make my own robust cables (inc. ribbon cables) and breakouts are ubiquitus.  I can imagine other people feeling differently though.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/20587606/45601123-1792e980-b9c5-11e8-8505-2ca3ff414ec9.png">

**Comment by gkasprow** [comment]
Such module would need some enclosure with brackets that fit the rack
![obraz](https://user-images.githubusercontent.com/4325054/45601696-48990b80-ba11-11e8-91e6-9debeb115c4e.png)

With such approach the PCB itself can be attached to the rack
![obraz](https://user-images.githubusercontent.com/4325054/45601747-2bb10800-ba12-11e8-807a-ee3e5ce89a84.png)

**Comment by gkasprow** [comment]
One could use such VHDCI to BNC adapter also to fanout Zotino signals. One can easily get HD68 <-> VHDCI cable and they would fit here.

**Comment by jordens** [comment]
For the VHDCI-BNC break-out, I think putting a 2U DIN rail insert ([this](https://www.canford.co.uk/Index/19-inch-rack-DIN-rail-terminal-frames/CANFORD-RACK-MOUNTING-DIN-RAIL-FRAME) or others) into a rack and then using those UM72 ([this](https://www.aliexpress.com/af/um72-pcb.html?SearchText=um72+pcb&blanktest=0&initiative_id=RS_20180917080702&origin=n&spm=2114.search0604.1.1.65e26a2bTWH2zW&jump=afs) or similar) open PCB modules (which have a lot of break-outs already available) is nicer. It solves the problem of mechanical strength.

**Comment by gkasprow** [comment]
@jordens Good idea. 
I would extend it slightly.
We can make variety of breakouts using these edge-to-edge connecting systems.
With VHDCI base module and i.e. 8 x BNC + Dsub + terminal block ones we can combine needed outputs in multiple ways.
Here is quick sketch presenting what I mean.
![obraz](https://user-images.githubusercontent.com/4325054/45636959-919c9e80-baa9-11e8-90de-5db83b6e3874.png)

**Comment by jordens** [comment]
Yes. The central VHDCI could expose its 32 channels in groups of 8 on its right and on its left. That would be four of those 10 pin edge connectors. Then a sub-module grabs the bottom 8 channels and simply forwards the remaining 32-8=24 channels to the next module on the right shifted (mechanically) by 8. Just to a barrel shift by 8 on each sub-module. The resulting stubs are at most the width of a single module. (I hope it's clear what I am trying to say. Otherwise I'll draw some ASCII art.)

**Comment by jordens** [comment]
You can arrange this in different ways. If you make each submodule completely point-symmetric (rotation by 180 degrees, by connecting the BNCs to both the bottom left and top right edge connector, like you did in the top row), then you can use them on either side. And you only need to decide whether you do 1,2 left/3,4 right or 1,2,3,4 left/1,2,3,4 right on the VHDCI module. Both will work. And with 1234/1234 you can do more patterns including everything you can do with the 12/34 arrangement.

**Comment by gkasprow** [comment]
Yes, the only issue is channel numbering (upside down), which means that additional panel would be needed.

**Comment by jordens** [comment]
No. The entire thing is 4-periodic. The "bottom" group-of-8-channels on a string of 5 modules are `|41|-|12|-|23|-|34|-|41|` Have the VHDCI module be the left one or the right one (`|41|` here) and the submodules will always nicely be numbered from left to right. And within each group there is also no issue.

**Comment by gkasprow** [comment]
I meant that if we print channel numbering, then rotate the module, the letters and digits would be upside down :)

**Comment by jordens** [comment]
Yes. Only the electrical interface needs to be rotationally symmetric, not the panel.

**Comment by gkasprow** [comment]
I'd like to avoid panels. The modules channels can be printed on the PCB. So we would have to live with  stubs anyway or use twice more board-to-board connectors like in the second conception. Of course some connectors may be not populated. In first conception with the central VHDCI module we would need just 8 connectors (and short stubs). In second conception with all slots populated we need 16 connectors. Their number can be however reduced to 10 because 6 are not active.

**Comment by jordens** [comment]
* [Banker EDGE2DSUB](https://github.com/sinara-hw/Banker_EDGE_2_DSUB/releases/download/v1.0rc1/Banker_EDGE_2_DSUB.PDF)
* [Banker EDGE2BNC](https://github.com/sinara-hw/Banker_EDGE_2_BNC/releases/download/v1.0rc1/Banker_EDGE_2_BNC.PDF)
* [Banker EDGE2SMA](https://github.com/sinara-hw/Banker_EDGE_2_SMA/releases/download/v1.0rc1/Banker_EDGE_2_SMA.PDF)
* [Banker EDGE2VHDCI](https://github.com/sinara-hw/Banker_VHDCI_2_EDGE/releases/download/v1.0rc1/Banker_VHDCI_2_EDGE.PDF)
* [Banker EDGE2VHDCI Buffered](https://github.com/sinara-hw/Banker_VHDCI_2_EDGE_Buffered/releases/download/v1.0rc1/Banker_VHDCI_2_EDGE_Buffered.PDF)
