### ISSUE TITLE
[I2C switch] move TEMP to port 0 (with EEPROM) and put EEM2 on port 5

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Banker#5]
That way either the FPGA or EEM2 can be the master (as it is now) and the other one can always be mapped on one of the slave ports (FPGA on port 1 and EEM2 on port 5).
Currently, if the FPGA is the master, EEM2 is either always connected or always disconnected to the I2C tree.
This is minor and can go into v1.1.

**Comment by gkasprow** [comment]
done
